package kelompok2.projectbp1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelompok2.projectbp1.koneksi;

public class FormOutputBarangKeluar extends javax.swing.JFrame {

  private Object JTable1;

    Statement st;
    ResultSet rs;
    koneksi koneksi;
    public FormOutputBarangKeluar() {
        initComponents();
         koneksi = new koneksi();
        load_data();
    }
    private void load_data() {
    Object header[] = {"ID_BARANG", "KATEGORI_BARANG", "NAMA_BARANG", "JUMLAH_STOK", "SATUAN","HARGA_SATUAN"};
    DefaultTableModel data = new DefaultTableModel(null, header);
    jTable1.setModel(data);

    String sql = "SELECT id_barang, kategori_barang, nama_barang, jumlah_stok,satuan,harga_satuan FROM persediaan";

    try {
        st = koneksi.con.createStatement();
        rs = st.executeQuery(sql);

        while (rs.next()) {
            String k1 = rs.getString("id_barang");
            String k2 = rs.getString("kategori_barang");
            String k3 = rs.getString("nama_barang");
            String k4 = rs.getString("jumlah_stok");
            String k5 = rs.getString("satuan");
            String k6 = rs.getString("harga_satuan");
            


            String k[] = {k1, k2, k3, k4, k5,k6};
            data.addRow(k);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    public void input_data() {
    try {
       
        String idBarang = ID_Barang.getText();
        String kategoriBarang = makanan.isSelected() ? "MAKANAN" : minuman.isSelected() ? "MINUMAN" : "";
        String namaBarang = Nama_Barang.getText();
        String jumlahStok = Jumlah_Stok.getText();
        String satuan = Satuan.getText();
        String hargaSatuan = Harga_Satuan.getText();

    
        if (idBarang.isEmpty() || kategoriBarang.isEmpty() || namaBarang.isEmpty() || 
            jumlahStok.isEmpty() || satuan == null || hargaSatuan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua data harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah Anda yakin ingin menyimpan data ini?", 
            "Konfirmasi Penyimpanan", 
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
        
            String sql = "INSERT INTO persediaan (id_barang, kategori_barang, nama_barang, jumlah_stok, satuan, harga_satuan) VALUES ('"
                + idBarang + "', '"
                + kategoriBarang + "', '"
                + namaBarang + "', '"
                + jumlahStok + "', '"
                + satuan + "', '"
                + hargaSatuan + "')";

            st = koneksi.con.createStatement();
            st.executeUpdate(sql);

       
            load_data();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            reset_form();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void reset_form() {
    ID_Barang.setText("");  
    makanan.setSelected(false);  
    minuman.setSelected(false); 
    Nama_Barang.setText("");  
    Jumlah_Stok.setText(""); 
    Nama_Barang.setText("");  
    Harga_Satuan.setText("");  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Harga_Satuan = new javax.swing.JTextField();
        Satuan = new javax.swing.JTextField();
        Jumlah_Stok = new javax.swing.JTextField();
        Nama_Barang = new javax.swing.JTextField();
        ID_Barang = new javax.swing.JTextField();
        makanan = new javax.swing.JRadioButton();
        minuman = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Tombol_Keluar_Barang = new javax.swing.JButton();
        Tombol_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM OUTPUT BARANG KELUAR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Masukan Data Berikut");

        jLabel3.setText("ID BARANG");

        jLabel4.setText("KATEGORI BARANG");

        jLabel5.setText("NAMA BARANG");

        jLabel6.setText("JUMLAH STOK");

        jLabel7.setText("SATUAN");

        jLabel8.setText("HARGA SATUAN");

        ID_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_BarangActionPerformed(evt);
            }
        });

        makanan.setText("MAKANAN");

        minuman.setText("MINUMAN");

        log.setColumns(20);
        log.setRows(5);
        jScrollPane2.setViewportView(log);

        jLabel9.setText("Pesan");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Harga_Satuan)
                            .addComponent(Satuan)
                            .addComponent(Jumlah_Stok)
                            .addComponent(Nama_Barang)
                            .addComponent(ID_Barang)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(makanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minuman))))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ID_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(makanan)
                            .addComponent(minuman))
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Nama_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Jumlah_Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Harga_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Tombol_Keluar_Barang.setText("KELUARKAN BARANG");
        Tombol_Keluar_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tombol_Keluar_BarangMouseClicked(evt);
            }
        });

        Tombol_Exit.setText("EXIT");
        Tombol_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tombol_ExitMouseClicked(evt);
            }
        });
        Tombol_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(Tombol_Keluar_Barang)
                        .addGap(235, 235, 235)
                        .addComponent(Tombol_Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tombol_Keluar_Barang)
                    .addComponent(Tombol_Exit))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_BarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_BarangActionPerformed

    private void Tombol_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tombol_ExitActionPerformed

    private void Tombol_Keluar_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol_Keluar_BarangMouseClicked
        // TODO add your handling code here:
        try {
        String id_barang = ID_Barang.getText();

        if (id_barang.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan ID_BARANG yang akan dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah Anda yakin ingin menghapus data ini?", 
            "Konfirmasi Penghapusan", 
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String sql_delete = "DELETE FROM persediaan WHERE id_barang = '" + id_barang + "'";
            st = koneksi.con.createStatement();
            st.executeUpdate(sql_delete);
            load_data();
            // Untuk Menampilkan Log pesan
            String log_pesan = log.getText();
            String kategori = minuman.isSelected() ? minuman.getText() : makanan.getText();
            String pesan = String.format("-- Data %s, ID: %s, berhasil dikeluarkan --\n", 
               kategori,ID_Barang.getText());
            log_pesan += pesan;
            log.setText(log_pesan);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            reset_form();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Tombol_Keluar_BarangMouseClicked

    private void Tombol_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol_ExitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_Tombol_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOutputBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOutputBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOutputBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOutputBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOutputBarangKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Harga_Satuan;
    private javax.swing.JTextField ID_Barang;
    private javax.swing.JTextField Jumlah_Stok;
    private javax.swing.JTextField Nama_Barang;
    private javax.swing.JTextField Satuan;
    private javax.swing.JButton Tombol_Exit;
    private javax.swing.JButton Tombol_Keluar_Barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea log;
    private javax.swing.JRadioButton makanan;
    private javax.swing.JRadioButton minuman;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
